In [1]:
import numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c= np.dot(a,b)
toc = time.time()
print ("c = " + str(c))
print ("Vectorized Version's Time: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print ("c = " + str(c))
print ("For-loop Version's Time: " + str(1000*(toc-tic)) + "ms")


c = 250220.053616
Vectorized Version's Time: 39.8728847504ms
c = 250220.053616
For-loop Version's Time: 584.136962891ms


In [2]:
A = np.array([[56, 0, 4.4, 68],[1.2, 104, 52, 8],[1.8, 135, 99, 0.9]])
print(A)

cal = A.sum(axis=0)
print ("\n\nTotal calories in 100 gms of Apples,Beef,Eggs,Potatoes:\n")
print cal

cal = cal.reshape(1,4)
assert(cal.shape == (1,4))

percent = 100*A/cal
print("\n\n Percentage of carbs/protein/fat in 100gm of Apples, Beef, Eggs, Protein:\n")
print(percent)


[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


Total calories in 100 gms of Apples,Beef,Eggs,Potatoes:

[  59.   239.   155.4   76.9]


 Percentage of carbs/protein/fat in 100gm of Apples, Beef, Eggs, Protein:

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [6]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print c

[[-0.011952   -0.0042856   0.01180021]
 [ 0.08949078  0.00397039 -0.05085906]
 [-0.17697978 -0.12421698 -0.07965918]]


In [1]:
import numpy as np
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [2]:
print (B.shape)

(4, 1)


In [4]:
print(B.shape[1])

1
